project_id = "rrlwabtzwvurhhfwpmiq"

[functions.stripe-webhook]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-appointment-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.process-mpesa-payment]
verify_jwt = false

[functions.google-ads-webhook]
verify_jwt = false

[functions.security-alert-webhook]
verify_jwt = false